services:
  # Express backend service
  backend:
    build: .
    container_name: quizhive_backend
    env_file: .env
    user: node
    ports:
      - '$PORT:$PORT'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  # MongoDB service
  mongo:
    container_name: quizehive_mongo
    image: mongo
    ports:
      - "127.0.0.1:$DB_PORT:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local